# Generated by Django 5.2.1 on 2025-05-27 11:06

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wallpapers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wallpaper', 'verbose_name_plural': 'Wallpapers'},
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='resolution',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='height',
            field=models.PositiveIntegerField(default=1080, verbose_name='Height (px)'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this wallpaper should be shown publicly', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail if not provided', upload_to='thumbnails/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_wallpapers', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='width',
            field=models.PositiveIntegerField(default=1920, verbose_name='Width (px)'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpapers', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the wallpaper', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Download Count'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(help_text='Upload high-quality wallpaper image', upload_to='wallpapers/%Y/%m/%d/', verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mark if this is premium content', verbose_name='Premium Content'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated tags for this wallpaper', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='title',
            field=models.CharField(help_text='Enter a descriptive title for the wallpaper', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['title'], name='wallpapers__title_23f7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['is_active'], name='wallpapers__is_acti_5e7f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['is_premium'], name='wallpapers__is_prem_34fe79_idx'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['created_at'], name='wallpapers__created_c46a5a_idx'),
        ),
    ]
