# Generated by Django 5.2.1 on 2025-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallpapers",
            "0002_alter_wallpaper_options_remove_wallpaper_resolution_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wallpaper",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from title if left blank",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
