# Generated by Django 5.2.1 on 2025-06-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0003_wallpaper_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
