# Generated by Django 5.2.1 on 2025-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0005_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallpaper",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated thumbnail if not provided",
                null=True,
                upload_to="thumbnails/%Y/%m/%d/",
                verbose_name="Thumbnail",
            ),
        ),
    ]
