# Generated by Django 5.2.1 on 2025-06-27 16:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("wallpapers", "0006_alter_wallpaper_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalWallpaper",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a descriptive title for the wallpaper",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the wallpaper",
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        help_text="Upload high-quality wallpaper image",
                        max_length=100,
                        verbose_name="Image File",
                    ),
                ),
                (
                    "thumbnail",
                    models.TextField(
                        blank=True,
                        help_text="Auto-generated thumbnail if not provided",
                        max_length=100,
                        null=True,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=1920, verbose_name="Width (px)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=1080, verbose_name="Height (px)"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download Count"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Mark if this is premium content",
                        verbose_name="Premium Content",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this wallpaper should be shown publicly",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title if left blank",
                        verbose_name="Slug",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="categories.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Wallpaper",
                "verbose_name_plural": "historical Wallpapers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
