# Generated by Django 5.2.1 on 2026-08-15 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wallpapers', '0007_historicalwallpaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwallpaper',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], default='landscape', help_text='Auto-detected from image dimensions', max_length=20, verbose_name='Orientation'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Users who bookmarked this wallpaper', related_name='favorite_wallpapers', to=settings.AUTH_USER_MODEL, verbose_name='Favorited By'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], default='landscape', help_text='Auto-detected from image dimensions', max_length=20, verbose_name='Orientation'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['orientation'], name='wallpapers__orienta_f0cfba_idx'),
        ),
    ]
