# Generated by Django 5.2.1 on 2025-06-12 07:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_bio_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.profile_image_upload_path,
                verbose_name="Profile Picture",
            ),
        ),
    ]
